# Generated by Django 4.1.7 on 2023-04-01 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_topic_rename_content_post_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-Updated', '-Created']},
        ),
        migrations.AddField(
            model_name='post',
            name='Topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Blog.topic'),
        ),
    ]
