# Generated by Django 4.1.7 on 2023-04-08 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='room',
            new_name='post',
        ),
    ]
